# Generated by Django 4.2.4 on 2023-10-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('token', models.CharField(default=None, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('no_of_users', models.BigIntegerField()),
                ('users', models.JSONField(default=None, verbose_name=models.CharField(default=None))),
            ],
        ),
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('login_id', models.CharField(default=None, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
                ('entry_check', models.BooleanField(default=False)),
                ('event_check', models.BooleanField(default=False)),
                ('gate_number', models.IntegerField(default=1)),
                ('event', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('login_id', models.CharField(default=None, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('entry_date', models.DateField()),
                ('exit_date', models.DateField()),
                ('no_of_events', models.IntegerField()),
                ('campus_entry', models.BooleanField(default=False)),
                ('event_entry', models.BooleanField(default=False)),
                ('entry', models.DateTimeField(blank=True, null=True)),
                ('exit_f', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.BigIntegerField()),
                ('events', models.JSONField(default=None, verbose_name=models.CharField(default=None))),
                ('events_verified', models.JSONField(default=None, verbose_name=models.BooleanField(default=False))),
            ],
        ),
    ]
