# Generated by Django 4.2.4 on 2023-10-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='token',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='users',
            field=models.JSONField(),
        ),
    ]
