# Generated by Django 4.2.4 on 2023-10-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_app', '0003_remove_user_campus_entry_remove_user_entry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='entry_date',
        ),
    ]
