# Generated by Django 4.2.4 on 2023-10-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_app', '0004_remove_user_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanner',
            name='password',
            field=models.CharField(default='a', max_length=8),
            preserve_default=False,
        ),
    ]
