# Generated by Django 4.2.4 on 2023-10-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='users',
            field=models.JSONField(default=None, verbose_name=models.CharField(default=None, max_length=20)),
        ),
        migrations.AlterField(
            model_name='user',
            name='events',
            field=models.JSONField(default=None, verbose_name=models.CharField(default=None, max_length=20)),
        ),
    ]
