# Generated by Django 4.2.4 on 2023-10-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_event_users_alter_user_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='campus_entry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='event_entry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='events_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='exit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='exit_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='no_of_events',
        ),
        migrations.AlterField(
            model_name='user',
            name='login_id',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
        ),
    ]
