# Generated by Django 4.2.4 on 2023-10-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_user_campus_entry_remove_user_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='aa', max_length=8),
            preserve_default=False,
        ),
    ]
